//http://benmcollins.github.io/libjwt/globals_eval.html

#ifndef CONFIGSELECTION_H
#define CONFIGSELECTION_H

/* These all are index to match Broker / IOT / Payload generation */
#define	IDX_HORNER		0
#define	IDX_AWS			1
#define	IDX_SPARKPLUG	2
#define	IDX_ATNT		3
#define	IDX_AZURE		4
#define	IDX_GOOGLE		5
#define	IDX_GENERIC		6
/* ------------------------------------------------------------------------------------------- */

/*** BROKER DETAILS ***/
#define MAX_BROKER_CONNECTION			2
#define BROKER_CLEAN_SESSION			TRUE
#define BROKER_KEEP_ALIVE				30	/* in sec */
#define BROKER_CLIENT_TYPE				3   /* PUBLISHER = 1, SUBSCRIBER = 2, PUB_SUB_BOTH = 3*/

/* ATNT */
#define ATNT_DEVICE_NAME				"OCS"
#define ATNT_DEVICE_ID					"c80ad86ccacfa015773a182d6dc6de9a"
#define ATNT_PRIMARY_ENDPOINT			"/devices/c80ad86ccacfa015773a182d6dc6de9a"
#define ATNT_PRIMARY_API_KEY			"b71654e9857aac858772b56398516b97"
#define ATNT_STREAMID					"x5_r1"

#define BROKER_ATNT_CLIENT_ID			ATNT_DEVICE_ID /* Should be Unique */
#define BROKER_ATNT_HOST				"api-m2x.att.com" /* IP or DOMAIN */
#define BROKER_ATNT_PORT				1883
#define BROKER_ATNT_UNAME				ATNT_PRIMARY_API_KEY
#define BROKER_ATNT_PASSWD				""

/* GOOGLE */
#define BROKER_GOOGLE_HOST				"mqtt.googleapis.com" /* IP or DOMAIN */
#define BROKER_GOOGLE_PORT				8883
#define BROKER_GOOGLE_UNAME				"unused"

/* BROKER_CLIENT_ID and BROKER_PASSWD will generated by using below parameters */
#define GOOGLE_PROJECT_ID				"TestMqttProject"
#define GOOGLE_REGIS_ID					"TestRegister"
#define GOOGLE_DEVICE_ID				"TestDevice"
#define GOOGLE_REGION					"asia-east1"
/* Refer http://benmcollins.github.io/libjwt/globals_eval.html */
#define GOOGLE_ALG_TYPE					4
#define GOOGLE_JWT_EXP_TIME				0 /* Min allowed 10 min (600 sec)*/

/* AZURE */
#define BROKER_AZURE_CLIENT_ID			"mytesthorneriotdevice" /* Should be Unique */
#define BROKER_AZURE_HOST				"hornerNewBroker.azure-devices.net" /* IP or DOMAIN */
#define BROKER_AZURE_PORT				8883
#define BROKER_AZURE_UNAME				"hornerNewBroker.azure-devices.net/mytesthorneriotdevice"
#define BROKER_AZURE_PASSWD				""

/* AWS */
#define BROKER_AWS_CLIENT_ID			"myAwsIotDevice_1" /* Should be Unique */
#define BROKER_AWS_HOST					"a3gcetrh91x0o6-ats.iot.eu-west-1.amazonaws.com" /* IP or DOMAIN */
#define BROKER_AWS_PORT					8883
#define BROKER_AWS_UNAME				""
#define BROKER_AWS_PASSWD				""

/* SPARKPLUG - Third Party */
#define BROKER_SPARKPLUG_CLIENT_ID		"mytestsparkplugnode" /* Should be Unique */
#define BROKER_SPARKPLUG_HOST			"162.255.87.22" /* IP or DOMAIN */
#define BROKER_SPARKPLUG_PORT			1883
#define BROKER_SPARKPLUG_UNAME			"ganesh"
#define BROKER_SPARKPLUG_PASSWD			"ganesh"

#define	SPARKPLUG_NAME_SPACE			"spBv1.0"
#define	SPARKPLUG_GROUP_ID				"hornerOCS"
#define	SPARKPLUG_NODE_ID				"x5"

/* Horner Brokers */
#define BROKER_HORNER_CLIENT_ID			"mytestsamplenode" /* Should be Unique */
#define BROKER_HORNER_HOST				"13.233.103.159"//"152.67.166.88" /* IP or DOMAIN */
#define BROKER_HORNER_PORT				1883
#define BROKER_HORNER_UNAME				"nitin"
#define BROKER_HORNER_PASSWD			"Horner@123"

/* GENERAL Brokers */
#define BROKER_GENERIC_CLIENT_ID		"mytestsamplenode" /* Should be Unique */
#define BROKER_GENERIC_HOST				"13.233.103.159"//"152.67.166.88" /* IP or DOMAIN */
#define BROKER_GENERIC_PORT				1883
#define BROKER_GENERIC_UNAME			""
#define BROKER_GENERIC_PASSWD			""
/* ------------------------------------------------------------------------------------------- */

/*** SSL/TLS ***/
/* ATNT */
#define ATNT_BROKER_SSL_ENABLE			FALSE
#define ATNT_CA_ONLY					FALSE
#define ATNT_BROKER_CACRT_FILE_NAME		""
#define ATNT_BROKER_CLCRT_FILE_NAME		""
#define ATNT_BROKER_CLKEY_FILE_NAME		""
#define ATNT_BROKER_CLKEY_PASSWD		""

/* AWS */
#define AWS_BROKER_SSL_ENABLE			TRUE
#define AWS_CA_ONLY						FALSE
#define AWS_BROKER_CACRT_FILE_NAME		"./aws/AmazonRootCA.pem"
#define AWS_BROKER_CLCRT_FILE_NAME		"./aws/certificate.pem.crt"
#define AWS_BROKER_CLKEY_FILE_NAME		"./aws/private.pem.key"
#define AWS_BROKER_CLKEY_PASSWD			""

/* AZURE */
#define AZURE_BROKER_SSL_ENABLE			TRUE
#define AZURE_CA_ONLY					FALSE
#define AZURE_BROKER_CACRT_FILE_NAME	"./azure/rootCA.crt"
#define AZURE_BROKER_CLCRT_FILE_NAME	"./azure/new-device.cert.pem"
#define AZURE_BROKER_CLKEY_FILE_NAME	"./azure/new-device.key.pem"
#define AZURE_BROKER_CLKEY_PASSWD		"1234"

/* GOOGLE */
#define GOOGLE_BROKER_SSL_ENABLE		TRUE
#define GOOGLE_CA_ONLY					TRUE
#define GOOGLE_BROKER_CACRT_FILE_NAME	"./google/roots.pem"
#define GOOGLE_BROKER_CLCRT_FILE_NAME	"./google/rsa_private1.pem" /* Private key to generate JWT */
#define GOOGLE_BROKER_CLKEY_FILE_NAME	""
#define GOOGLE_BROKER_CLKEY_PASSWD		""

/* SPARKPLUG */
#define SPARKPLUG_BROKER_SSL_ENABLE			FALSE
#define SPARKPLUG_CA_ONLY					FALSE
#define SPARKPLUG_BROKER_CACRT_FILE_NAME	""
#define SPARKPLUG_BROKER_CLCRT_FILE_NAME	""
#define SPARKPLUG_BROKER_CLKEY_FILE_NAME	""
#define SPARKPLUG_BROKER_CLKEY_PASSWD		""

/* HORNER */
#define HORNER_BROKER_SSL_ENABLE			FALSE
#define HORNER_CA_ONLY						FALSE
#define HORNER_BROKER_CACRT_FILE_NAME		""
#define HORNER_BROKER_CLCRT_FILE_NAME		""
#define HORNER_BROKER_CLKEY_FILE_NAME		""
#define HORNER_BROKER_CLKEY_PASSWD			""

/* GENERAL */
#define GENERIC_BROKER_SSL_ENABLE			FALSE
#define GENERIC_CA_ONLY						FALSE
#define GENERIC_BROKER_CACRT_FILE_NAME		""
#define GENERIC_BROKER_CLCRT_FILE_NAME		""
#define GENERIC_BROKER_CLKEY_FILE_NAME		""
#define GENERIC_BROKER_CLKEY_PASSWD			""
/* ------------------------------------------------------------------------------------------- */

/*** SUBSCRIBE & PUBLISH Details ***/
/* HORNER PROFILE */
/* Subscribe Details */
#define HP_BROKER_SUB_COUNT					0
#define HP_BROKER_SUB_TOPIC					""
#define HP_BROKER_SUB_QOS					0

/* Publish Details */
#define HP_BROKER_PUB_COUNT					1
#define HP_BROKER_PUB_QOS					2
#define HP_BROKER_PUB_RETAINED				FALSE
#define HP_BROKER_PUB_TOPIC					"Hist/2/1/FirmwareTest"
#define HP_BROKER_PUB_PERIODIC_TIME			3 /*in sec*/

/* AWS */
/* Subscribe Details */
#define AWS_BROKER_SUB_COUNT				0
#define AWS_BROKER_SUB_TOPIC				""
#define AWS_BROKER_SUB_QOS					0

/* Publish Details */
#define AWS_BROKER_PUB_COUNT				1
#define AWS_BROKER_PUB_QOS					0
#define AWS_BROKER_PUB_RETAINED				FALSE
#define AWS_BROKER_PUB_TOPIC				"Hist/aws"
#define AWS_BROKER_PUB_PERIODIC_TIME		5 /*in sec*/

/* GOOGLE */
/* Subscribe Details */
#define GOOGLE_BROKER_SUB_COUNT				0
#define GOOGLE_BROKER_SUB_TOPIC				""
#define GOOGLE_BROKER_SUB_QOS				0

/* Publish Details */
#define GOOGLE_BROKER_PUB_COUNT				1
#define GOOGLE_BROKER_PUB_QOS				2
#define GOOGLE_BROKER_PUB_RETAINED			FALSE
#define GOOGLE_BROKER_PUB_TOPIC				""
#define GOOGLE_BROKER_PUB_PERIODIC_TIME		5 /*in sec*/

/* ATNT */
/* Subscribe Details */
#define ATNT_BROKER_SUB_COUNT				0
#define ATNT_BROKER_SUB_TOPIC				""
#define ATNT_BROKER_SUB_QOS					0

/* Publish Details */
#define ATNT_BROKER_PUB_COUNT				1
#define ATNT_BROKER_PUB_QOS					2
#define ATNT_BROKER_PUB_RETAINED			FALSE
#define ATNT_BROKER_PUB_TOPIC				""
#define ATNT_BROKER_PUB_PERIODIC_TIME		5 /*in sec*/

/* GENERIC PROFILE */
/* Subscribe Details */
#define GENERIC_BROKER_SUB_COUNT			0
#define GENERIC_BROKER_SUB_TOPIC			""
#define GENERIC_BROKER_SUB_QOS				0

/* Publish Details */
#define GENERIC_BROKER_PUB_COUNT			1
#define GENERIC_BROKER_PUB_QOS				2
#define GENERIC_BROKER_PUB_RETAINED			FALSE
#define GENERIC_BROKER_PUB_TOPIC			"Hist/2/1/FirmwareTest"
#define GENERIC_BROKER_PUB_PERIODIC_TIME	5 /*in sec*/
/* ------------------------------------------------------------------------------------------- */

/*** Others ***/
#define BROKER_TLSV_1						"tlsv1"
#define BROKER_TLSV_1_1						"tlsv1.1"
#define BROKER_TLSV_1_2						"tlsv1.2"
#endif

/* EOF */